Add https support

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,9 +2,9 @@ name: main
 
 on:
   push:
-    branches: 
+    branches:
       - main
-  
+
 permissions:
   packages: write
 
@@ -15,71 +15,71 @@ env:
   DEPLOY_USER: deploy
   DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
   DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
+  ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
 
 jobs:
-
   validate-env:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Validate environment variables
-      run: |
-        if [ -z "${{ env.DEPLOY_HOST }}" ] || [ -z "${{ env.DEPLOY_PRIVATE_KEY }}" ]; then
-          echo "Failed environment variable validation"
-          exit 1
-        fi
-        exit 0
+      - name: Validate environment variables
+        run: |
+          if [ -z "${{ env.DEPLOY_HOST }}" ] || [ -z "${{ env.DEPLOY_PRIVATE_KEY }}" ]; then
+            echo "Failed environment variable validation"
+            exit 1
+          fi
+          exit 0
 
   build-app:
     runs-on: ubuntu-latest
 
     needs:
       - validate-env
-      
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Setup Node.js
-      uses: actions/setup-node@v4.2.0
+      - name: Setup Node.js
+        uses: actions/setup-node@v4.2.0
 
-    - name: Install node dependencies
-      run: npm install
+      - name: Install node dependencies
+        run: npm install
 
-    - name: Generate css
-      run: npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css
-      
-    - name: Set up Docker
-      uses: docker/setup-docker-action@v4.1.0
+      - name: Generate css
+        run: npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css
 
-    - name: Login to docker
-      uses: docker/login-action@v3.3.0
-      with:
-        registry: ${{ env.CONTAINER_REGISTRY }}
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Docker
+        uses: docker/setup-docker-action@v4.1.0
 
-    - name: Generate image metadata
-      id: meta
-      uses: docker/metadata-action@v5.6.1
-      with:
-        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
-        tags: |
-          type=ref,event=branch
-          type=ref,event=pr
-          type=semver,pattern={{version}}
-          type=semver,pattern={{major}}.{{minor}}
-          type=sha,format=long
-          type=raw,value=latest,enable={{is_default_branch}}
-    
-    - name: Build and push app image
-      uses: docker/build-push-action@v6.14.0
-      with:
-        context: .
-        push: true
-        tags: ${{ steps.meta.outputs.tags }}
-        labels: ${{ steps.meta.outputs.labels }}
-              
+      - name: Login to docker
+        uses: docker/login-action@v3.3.0
+        with:
+          registry: ${{ env.CONTAINER_REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Generate image metadata
+        id: meta
+        uses: docker/metadata-action@v5.6.1
+        with:
+          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
+          tags: |
+            type=ref,event=branch
+            type=ref,event=pr
+            type=semver,pattern={{version}}
+            type=semver,pattern={{major}}.{{minor}}
+            type=sha,format=long
+            type=raw,value=latest,enable={{is_default_branch}}
+
+      - name: Build and push app image
+        uses: docker/build-push-action@v6.14.0
+        with:
+          context: .
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+
   deploy-app:
     runs-on: ubuntu-latest
 
@@ -88,23 +88,24 @@ jobs:
       - build-app
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Create stack env file
-      run: |
-        echo "APP_IMAGE_TAG=sha-${{ github.sha }}" >> ./envfile
+      - name: Create stack env file
+        run: |
+          echo "APP_IMAGE_TAG=sha-${{ github.sha }}" >> ./envfile
+          echo "ACME_EMAIL=${{ env.ACME_EMAIL }}" >> ./envfile
 
-    - name: Deploy app stack
-      uses: cssnr/stack-deploy-action@v1
-      with:
-        name: ${{ env.STACK_NAME }}
-        file: ./compose.yaml
-        env_file: ./envfile
-        host: ${{ env.DEPLOY_HOST }}
-        user: ${{ env.DEPLOY_USER }}
-        ssh_key: ${{ env.DEPLOY_PRIVATE_KEY }}
-        registry_auth: true
-        registry_host: ${{ env.CONTAINER_REGISTRY }}
-        registry_user: ${{ github.actor }}
-        registry_pass: ${{ secrets.GITHUB_TOKEN }}
+      - name: Deploy app stack
+        uses: cssnr/stack-deploy-action@v1
+        with:
+          name: ${{ env.STACK_NAME }}
+          file: ./compose.yaml
+          env_file: ./envfile
+          host: ${{ env.DEPLOY_HOST }}
+          user: ${{ env.DEPLOY_USER }}
+          ssh_key: ${{ env.DEPLOY_PRIVATE_KEY }}
+          registry_auth: true
+          registry_host: ${{ env.CONTAINER_REGISTRY }}
+          registry_user: ${{ github.actor }}
+          registry_pass: ${{ secrets.GITHUB_TOKEN }}
